# Generated by Django 5.2 on 2025-06-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
